version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 19 
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Running npm install..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - npm run build
artifacts:
  files:
    - '**/*'
